modLoader="javafml" # The type of mod loader, Java FML for Forge
loaderVersion="47," # For Minecraft 1.20.1, Forge version 39.0.0 (example)
license="All rights reserved" # Replace with your mod's license

[[mods]] # The mods section, each mod should have this section
modId="mirapose" # Your mod ID, should be all lowercase and match the mod ID you use in code
version="1.0.0" # The version of your mod
displayName="mirapose" # The display name of your mod
description='''
mirapose.
''' # A description of your mod

# Here you can define dependencies and other metadata
